SELECT CAR_ID, CAR_TYPE, FEE
FROM (
  SELECT
    C.CAR_ID,
    C.CAR_TYPE,
    TRUNCATE(C.DAILY_FEE * 30 * (1 - D.DISCOUNT_RATE / 100), 0) AS FEE
  FROM CAR_RENTAL_COMPANY_CAR C
  JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
    ON C.CAR_TYPE = D.CAR_TYPE AND D.DURATION_TYPE = '30일 이상'
  WHERE C.CAR_TYPE IN ('세단', 'SUV')
    AND C.CAR_ID NOT IN (
      SELECT H.CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
      WHERE NOT (H.END_DATE < '2022-11-01' OR H.START_DATE > '2022-11-30')
    )
) X
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;