-- 코드를 작성해주세요
SELECT ID,
    CASE
        WHEN PCT <= 0.25 THEN 'CRITICAL'
        WHEN PCT <= 0.5 THEN 'HIGH'
        WHEN PCT <= 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM (SELECT ID, PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) PCT FROM ECOLI_DATA) E1
ORDER BY ID;