-- 코드를 입력하세요
WITH U2021 AS (
    SELECT USER_ID, YEAR(JOINED) YEAR, MONTH(JOINED) MONTH
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
), TOTAL AS (SELECT COUNT(*) AS CNT FROM U2021)
SELECT
    YEAR(SALES_DATE) YEAR,
    MONTH(SALES_DATE) MONTH,
    COUNT(DISTINCT O.USER_ID) PURCHASED_USERS, ROUND(COUNT(DISTINCT O.USER_ID) / CNT, 1) PURCHASED_RATIO
FROM ONLINE_SALE O
JOIN U2021 U USING(USER_ID)
CROSS JOIN TOTAL T
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR, MONTH;