-- 코드를 작성해주세요
WITH RECURSIVE GEN AS (
    SELECT ID, 1 AS GLEVEL
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT C.ID, G.GLEVEL + 1
    FROM ECOLI_DATA C
    JOIN GEN G ON C.PARENT_ID = G.ID
)

SELECT COUNT(*) COUNT, GLEVEL AS GENERATION
FROM GEN G
LEFT JOIN ECOLI_DATA C ON G.ID = C.PARENT_ID
WHERE PARENT_ID IS NULL
GROUP BY GLEVEL
ORDER BY GLEVEL;