-- 코드를 입력하세요
-- 코드를 입력하세요
SELECT FLAVOR
FROM (
    SELECT FLAVOR, (F.TOTAL_ORDER + SUM(J.TOTAL_ORDER)) TOTAL
    FROM FIRST_HALF AS F
    JOIN JULY AS J USING(FLAVOR)
    GROUP BY FLAVOR
    ORDER BY TOTAL DESC
) AS T
LIMIT 3;