-- 코드를 입력하세요
WITH MEM_CNT AS (
    SELECT MEMBER_ID, COUNT(*) CNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
)
SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM (
    SELECT MEMBER_ID
    FROM MEM_CNT
    WHERE CNT = (SELECT MAX(CNT) FROM MEM_CNT)
) AS TOP
JOIN MEMBER_PROFILE P ON TOP.MEMBER_ID = P.MEMBER_ID
JOIN REST_REVIEW R ON TOP.MEMBER_ID = R.MEMBER_ID
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT;