-- 코드를 작성해주세요
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO
JOIN FISH_NAME_INFO USING(FISH_TYPE)
WHERE (FISH_TYPE, LENGTH)
IN (SELECT FISH_TYPE, MAX(LENGTH) OVER(PARTITION BY FISH_TYPE) FROM FISH_INFO)
ORDER BY ID;