SELECT
    CASE
        WHEN D.SKILL_CODE & S.FE AND D.SKILL_CODE &S.PY THEN 'A'
        WHEN D.SKILL_CODE & S.CSH THEN 'B'
        ELSE 'C'
    END GRADE, D.ID, D.EMAIL
FROM DEVELOPERS D
CROSS JOIN (
    SELECT
        SUM(CASE WHEN CATEGORY = 'Front End' THEN CODE ELSE 0 END) FE,
        SUM(CASE WHEN NAME = 'Python' THEN CODE ELSE 0 END) PY,
        SUM(CASE WHEN NAME = 'C#' THEN CODE ELSE 0 END) CSH
    FROM SKILLCODES
) S
WHERE D.SKILL_CODE & (S.FE | S.CSH) > 0
ORDER BY GRADE, D.ID